#!/bin/sh

GPG_CONF="$HOME/.gnupg/gpg.conf"
GPG_AGENT_CONF="$HOME/.gnupg/gpg-agent.conf"

help() {
    if [ -n "$1" ]; then
        echo "Error: $1"
        echo ""
    fi

    echo "GPG Utils"
    echo ""
    echo "Usage: gpgg <help | list | config>"
    echo ""
    echo "Commands:"
    echo "  help, h      Show this help"
    echo "  list, l      List secret keys"
    echo "  config, c    Configure GPG"
}

help_config() {
    if [ -n "$1" ]; then
        echo "Error: $1"
        echo ""
    fi

    echo "GPG Utils"
    echo ""
    echo "Usage: gpgg config <touchid | tty>"
    echo ""
    echo "Commands:"
    echo "  touchid    Use pinentry-touchid"
    echo "  tty        Use default TTY pinentry"
}

if [ $# -eq 0 ]; then
    help
    exit 1
fi

case "$1" in
    help | h)
        help
        ;;
    list | l)
        gpg --list-secret-keys --keyid-format LONG
        ;;
    config | c)
        if [ -z "$2" ]; then
            help_config
            exit 1
        fi

        case "$2" in
            touchid)
                if ! grep -q "no-tty" "$GPG_CONF"; then
                    echo "no-tty" >> "$GPG_CONF"
                fi

                if ! grep -q "pinentry-program /opt/homebrew/bin/pinentry-touchid" "$GPG_AGENT_CONF"; then
                    echo "pinentry-program /opt/homebrew/bin/pinentry-touchid" >> "$GPG_AGENT_CONF"
                fi

                killall gpg-agent

                cat "$GPG_CONF"
                cat "$GPG_AGENT_CONF"
                ;;
            tty)
                if grep -q "no-tty" "$GPG_CONF"; then
                    sed -i '' '/no-tty/d' "$GPG_CONF"
                fi

                if grep -q "pinentry-program /opt/homebrew/bin/pinentry-touchid" "$GPG_AGENT_CONF"; then
                    sed -i '' '/pinentry-program \/opt\/homebrew\/bin\/pinentry-touchid/d' "$GPG_AGENT_CONF"
                fi

                killall gpg-agent

                cat "$GPG_CONF"
                cat "$GPG_AGENT_CONF"
                ;;
            *)
                help_config "Unknown config"
                exit 1
                ;;
        esac
        ;;
    *)
        help "Unknown command"
        exit 1
        ;;
esac
